#!/usr/bin/env bash

set -e

# Determine the OS
OS="$(uname -s)"

# Set the config file based on the OS
if [[ "$OS" == "Darwin" ]]; then
    echo "MacOS detected using './install.conf.yaml'
    "
    CONFIG="install.conf.yaml"
elif [[ "$OS" =~ MINGW|CYGWIN|MSYS ]]; then
    CONFIG="windows-install.conf.yaml"
    echo "Windows detected using './windows-install.conf'"
else
    echo "Unsupported operating system: $OS"
    exit 1
fi

DOTBOT_DIR="dotbot"

DOTBOT_BIN="bin/dotbot"
BASEDIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"

cd "${BASEDIR}"
git -C "${DOTBOT_DIR}" submodule sync --quiet --recursive
git submodule update --init --recursive "${DOTBOT_DIR}"

"${BASEDIR}/${DOTBOT_DIR}/${DOTBOT_BIN}" -d "${BASEDIR}" -c "${CONFIG}" "${@}"